name: Rebuild Site on Notion Update

on:
  # Manual trigger
  workflow_dispatch:
  
  # Webhook trigger (requires setting up a webhook from Notion)
  repository_dispatch:
    types: [notion-update]
  
  # Scheduled rebuild (optional - runs daily at 9 AM UTC)
  schedule:
    - cron: '0 9 * * *'

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages-notion"
  cancel-in-progress: false

jobs:
  build:
    environment: github-pages
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm ci

      - name: Build with Notion data
        env:
          VITE_NOTION_TOKEN: ${{ secrets.NOTION_TOKEN }}
          VITE_NOTION_DATABASE_ID: ${{ secrets.NOTION_DATABASE_ID }}
          VITE_USE_NOTION: 'true'
        run: npm run build

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './dist'

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
